services:
  chatapi:
    container_name: chat_api
    build:
      context: .
      dockerfile: src/Hosts/Moneo.Hosts.Chat.Api/Dockerfile
    image: moneo-chat-api:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      Moneo__TaskManagement__BaseUrl: http://taskapi:8080
      Moneo__TaskManagement__ApiKey: 123456
      Telegram__BotToken: 599186770:AAEaRIjKJNh0G5W2ySfqUi7CrXInuC9Wr4s
      Telegram__MasterConversationId: 122243374
      Telegram__CallbackToken: ccccccvljldelhvjclhulingujnhvgkuvbilllgddjjd
    ports:
      - "5080:8080"
    networks:
      - moneo
        
  taskapi:
    container_name: task_api
    build:
      context: .
      dockerfile: src/Hosts/Moneo.TaskManagement.Api/Dockerfile
    image: moneo-tasks-api:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      Moneo__DatabaseProvider: Sqlite
      Moneo__DatabaseConnectionString: Data Source=tasks.sqlite
      Moneo__Notification__BaseUrl: http://chatapi:8080
      Moneo__Notification__ApiKey: 123456
      Telegram__BotToken: 599186770:AAEaRIjKJNh0G5W2ySfqUi7CrXInuC9Wr4s
      Telegram__MasterConversationId: 122243374
      Telegram__CallbackToken: ccccccvljldelhvjclhulingujnhvgkuvbilllgddjjd
    ports:
      - "5090:8080"
    networks:
      - moneo
        
networks:
    moneo:
        driver: bridge
