version: "3.8"
services:
  poller:
    image: moneo-poller
    volumes:
      - ./appsettings.json:/App/appsettings.json
  moneo.taskmanagment.api:
    image: moneo.taskmanagment.api
    build:
      context: .
      dockerfile: src/Moneo.Hosts/Moneo.TaskManagment.Api/Dockerfile

  moneo.telegramchat.api:
    image: moneo.telegramchat.api
    build:
      context: .
      dockerfile: src/Hosts/Moneo.TelegramChat.Api/Dockerfile
